# Pandas

In [16]:
import pandas as pd

## Create

In [9]:

x_data = {
    "Name": ["a", "b", "c"],
    "Age": [11, 12, 13]
}
xdf = pd.DataFrame(x_data)
xdf

  Name  Age
0    a   11
1    b   12
2    c   13

In [10]:
x_data = {
    "Name": ["a", "b", "c"],
    "Age": [11, 12, 13]
}

In [11]:
x_data = {
    "Name": ["aria", "bahram", "nooshin", "farhad"],
    "Age": [11, 12, 13, 14]
}

xdf = pd.DataFrame(x_data)
xdf

      Name  Age
0     aria   11
1   bahram   12
2  nooshin   13
3   farhad   14

## Read data

In [12]:
df = pd.read_csv("data.csv")
df

       Name  Age   Salary
0    ROZHIN   35   7515.0
1   DARIUSH   47   6050.0
2     ROZAN   29   7158.0
3     BABAK   28   9956.0
4    FARHAD   18   6693.0
5      NIMA   65   7563.0
6     SHADI   43   7835.0
7     ELNAZ   45   6191.0
8    MEHRAN   45   9328.0
9     SHADI   29   9233.0
10   ROZHIN   29   9345.0
11   ROXANA   31   7491.0
12     TARA   49   9781.0
13    ELNAZ   43   7402.0
14   FARHAD   62   5841.0
15     ARIA   37   6371.0
16   MEHRAN   24   7208.0
17     NIMA   57   7168.0
18    Atusa   35      NaN
19    Atusa   35  10000.0

In [13]:
df.head()

      Name  Age  Salary
0   ROZHIN   35  7515.0
1  DARIUSH   47  6050.0
2    ROZAN   29  7158.0
3    BABAK   28  9956.0
4   FARHAD   18  6693.0

In [14]:
df['Salary'] = df['Salary'].str.replace('$', '', regex=False).astype(float)
df.describe()

AttributeError: Can only use .str accessor with string values, not floating

In [ ]:

df["Name"]

In [ ]:

df["Name"],df["Salary"]

In [ ]:

df.iloc[2,:]

In [ ]:
df.iloc[2, 1]

In [ ]:
df.iloc[4,2]

In [ ]:
df.iloc[5,0]

## Filtering

In [ ]:
df

In [ ]:

filtered_df = df[df["Salary"]> 8000]
filtered_df

## Sorting

In [ ]:

df

In [ ]:

df_sorted = df.sort_values("Salary")
df_sorted

In [ ]:

df_sorted_x = df.sort_values("Salary", ascending=True)
df_sorted_x
df_sorted_x = df.sort_values("Salary", ascending=False)
df_sorted_x

## Subset

In [ ]:
df_subset = df.loc[2: 4, ["Name", "Salary"]]
df_subset

## Grouping

In [ ]:
df_grouped = df.groupby("Age")
df_grouped

In [ ]:
df_grouped.count()

## Add a new column

In [ ]:

df["Test"] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 113, 14, 15, 16,17, 18]
df.to_csv("data.csv", index=False)
df

## Delete a column

In [ ]:
df

df.drop("Test", axis=1, inplace=True)
df.to_csv("data.csv", index=False)
df

## Add a new record

In [ ]:
len(df)

In [ ]:
df.loc[len(df)] = {
    "Name": "Atusa",
    "Age": 35,
    "Salary": 10000
     
}

df

In [ ]:
df.isna()

In [ ]:
df.dropna()
df

In [ ]:
df.to_csv("data.csv", index=False)
df

In [ ]:

df.loc[len(df)] = {
    "Name": "Azita",
    "Age": 35
    
     
}

df

In [ ]:

df.fillna(0)

In [ ]:
df.to_csv("new_data.csv", )
df

In [ ]:
df.fillna(0)
df
df.to_csv("new_data.csv", index=False)
df

In [17]:
df2 = pd.read_csv("new_data.csv")
df2
df2.fillna(0)
df2
df2.to_csv("new_data.csv", index=False)
df

       Name  Age   Salary
0    ROZHIN   35   7515.0
1   DARIUSH   47   6050.0
2     ROZAN   29   7158.0
3     BABAK   28   9956.0
4    FARHAD   18   6693.0
5      NIMA   65   7563.0
6     SHADI   43   7835.0
7     ELNAZ   45   6191.0
8    MEHRAN   45   9328.0
9     SHADI   29   9233.0
10   ROZHIN   29   9345.0
11   ROXANA   31   7491.0
12     TARA   49   9781.0
13    ELNAZ   43   7402.0
14   FARHAD   62   5841.0
15     ARIA   37   6371.0
16   MEHRAN   24   7208.0
17     NIMA   57   7168.0
18    Atusa   35      NaN
19    Atusa   35  10000.0

In [ ]:
df2.isna()

In [19]:
df2.fillna(0)
df2

       Name  Age   Salary
0    ROZHIN   35   7515.0
1   DARIUSH   47   6050.0
2     ROZAN   29   7158.0
3     BABAK   28   9956.0
4    FARHAD   18   6693.0
5      NIMA   65   7563.0
6     SHADI   43   7835.0
7     ELNAZ   45   6191.0
8    MEHRAN   45   9328.0
9     SHADI   29   9233.0
10   ROZHIN   29   9345.0
11   ROXANA   31   7491.0
12     TARA   49   9781.0
13    ELNAZ   43   7402.0
14   FARHAD   62   5841.0
15     ARIA   37   6371.0
16   MEHRAN   24   7208.0
17     NIMA   57   7168.0
18    Atusa   35      NaN
19    Atusa   35  10000.0
20    Azita   35      NaN

In [22]:
df2["Test"] = [1, 2, 3, 4, 5, 6, 11, 22, 33, 44, 55, 66, 111, 112, 113, 114, 115, 116, 117, 121, 131]
df2

       Name  Age   Salary  Test
0    ROZHIN   35   7515.0     1
1   DARIUSH   47   6050.0     2
2     ROZAN   29   7158.0     3
3     BABAK   28   9956.0     4
4    FARHAD   18   6693.0     5
5      NIMA   65   7563.0     6
6     SHADI   43   7835.0    11
7     ELNAZ   45   6191.0    22
8    MEHRAN   45   9328.0    33
9     SHADI   29   9233.0    44
10   ROZHIN   29   9345.0    55
11   ROXANA   31   7491.0    66
12     TARA   49   9781.0   111
13    ELNAZ   43   7402.0   112
14   FARHAD   62   5841.0   113
15     ARIA   37   6371.0   114
16   MEHRAN   24   7208.0   115
17     NIMA   57   7168.0   116
18    Atusa   35      NaN   117
19    Atusa   35  10000.0   121
20    Azita   35      NaN   131

In [ ]:
df.fillna(0, inplace=True)
df2
df2 =

       Name  Age   Salary  Test
0    ROZHIN   35   7515.0     1
1   DARIUSH   47   6050.0     2
2     ROZAN   29   7158.0     3
3     BABAK   28   9956.0     4
4    FARHAD   18   6693.0     5
5      NIMA   65   7563.0     6
6     SHADI   43   7835.0    11
7     ELNAZ   45   6191.0    22
8    MEHRAN   45   9328.0    33
9     SHADI   29   9233.0    44
10   ROZHIN   29   9345.0    55
11   ROXANA   31   7491.0    66
12     TARA   49   9781.0   111
13    ELNAZ   43   7402.0   112
14   FARHAD   62   5841.0   113
15     ARIA   37   6371.0   114
16   MEHRAN   24   7208.0   115
17     NIMA   57   7168.0   116
18    Atusa   35      NaN   117
19    Atusa   35  10000.0   121
20    Azita   35      NaN   131

In [25]:
df2.to_csv("new_data.csv", index=False)
df2

       Name  Age   Salary  Test
0    ROZHIN   35   7515.0     1
1   DARIUSH   47   6050.0     2
2     ROZAN   29   7158.0     3
3     BABAK   28   9956.0     4
4    FARHAD   18   6693.0     5
5      NIMA   65   7563.0     6
6     SHADI   43   7835.0    11
7     ELNAZ   45   6191.0    22
8    MEHRAN   45   9328.0    33
9     SHADI   29   9233.0    44
10   ROZHIN   29   9345.0    55
11   ROXANA   31   7491.0    66
12     TARA   49   9781.0   111
13    ELNAZ   43   7402.0   112
14   FARHAD   62   5841.0   113
15     ARIA   37   6371.0   114
16   MEHRAN   24   7208.0   115
17     NIMA   57   7168.0   116
18    Atusa   35      NaN   117
19    Atusa   35  10000.0   121
20    Azita   35      NaN   131

In [28]:
df2 = df2.fillna(0)
df2

       Name  Age   Salary  Test
0    ROZHIN   35   7515.0     1
1   DARIUSH   47   6050.0     2
2     ROZAN   29   7158.0     3
3     BABAK   28   9956.0     4
4    FARHAD   18   6693.0     5
5      NIMA   65   7563.0     6
6     SHADI   43   7835.0    11
7     ELNAZ   45   6191.0    22
8    MEHRAN   45   9328.0    33
9     SHADI   29   9233.0    44
10   ROZHIN   29   9345.0    55
11   ROXANA   31   7491.0    66
12     TARA   49   9781.0   111
13    ELNAZ   43   7402.0   112
14   FARHAD   62   5841.0   113
15     ARIA   37   6371.0   114
16   MEHRAN   24   7208.0   115
17     NIMA   57   7168.0   116
18    Atusa   35      0.0   117
19    Atusa   35  10000.0   121
20    Azita   35      0.0   131

In [29]:
df2.to_csv("new_data.csv", index=False)
df2

       Name  Age   Salary  Test
0    ROZHIN   35   7515.0     1
1   DARIUSH   47   6050.0     2
2     ROZAN   29   7158.0     3
3     BABAK   28   9956.0     4
4    FARHAD   18   6693.0     5
5      NIMA   65   7563.0     6
6     SHADI   43   7835.0    11
7     ELNAZ   45   6191.0    22
8    MEHRAN   45   9328.0    33
9     SHADI   29   9233.0    44
10   ROZHIN   29   9345.0    55
11   ROXANA   31   7491.0    66
12     TARA   49   9781.0   111
13    ELNAZ   43   7402.0   112
14   FARHAD   62   5841.0   113
15     ARIA   37   6371.0   114
16   MEHRAN   24   7208.0   115
17     NIMA   57   7168.0   116
18    Atusa   35      0.0   117
19    Atusa   35  10000.0   121
20    Azita   35      0.0   131